repos:
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 3.2.19
    hooks:
      - id: checkov
        args:
          - --quiet
          - --compact
          - --skip-check=CKV_AWS_338,CKV_DOCKER_2,CKV_DOCKER_3,CKV_AWS_158
        files: .*
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-fmt
        args: [-w]
        files: ^seaweed_events/
      - id: go-vet-mod
        files: ^seaweed_events/
      - id: go-build-mod
        files: ^seaweed_events/
      - id: go-mod-tidy
        files: ^seaweed_events/
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.64.0
    hooks:
      - id: golangci-lint
        files: ^seaweed_events/
        entry: bash -c 'cd seaweed_events && go mod download && golangci-lint run'
        pass_filenames: false
